version: '3.9'

services:
  workspace:
    container_name: java-stream-course
    build:
      context: ./docker/workspace
      args:
        USERNAME: vscode
        USER_GROUP_NAME: vscode
        USER_UID: 1000
        USER_GID: 1000
    tty: true
    volumes:
      - ../:/home/vscode/workspace:cached
    ports:
      - 5555:5555
